/* Generated by serviceWorkerPlugin. Do not edit by hand. */
const CACHE = 'tarsia-15d0e452d8a2ffa9';
const PRECACHE = [
  "/",
  "/assets/index-CnO8ZIvm.css",
  "/assets/index-DV943Vjy.js",
  "/fonts/OFL-instrumentsans.txt",
  "/fonts/instrument-sans.woff2",
  "/icons/favicon.svg",
  "/icons/icon-180.png",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-512.png",
  "/icons/tarsia.ico",
  "/manifest.webmanifest"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);

      // `cache: 'reload'` rather than `cache.addAll`, which would have been shorter.
      // addAll goes through the browser's own HTTP cache, and static hosts put an
      // expiry on the page — so a worker installing minutes after a deploy could
      // store the previous page against this deploy's asset names and pin the two
      // together for good. This asks the network every time.
      //
      // One rejection fails the whole install, which is the behaviour to keep: a
      // half-filled cache is an app that starts and then breaks somewhere later.
      await Promise.all(
        PRECACHE.map(async (path) => {
          const response = await fetch(new Request(path, { cache: 'reload' }));
          if (!response.ok) throw new Error('Could not precache ' + path);
          await cache.put(path, response);
        }),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name)));
      await self.clients.claim();
    })(),
  );
});

// Cached responses are looked up ignoring both the query string and the Vary header.
// Vary matters: many static hosts send `Vary: Origin` or `Vary: Accept-Encoding`, and
// with the default rules a stored response is only returned when the new request's
// headers match those of the request that stored it. Without this, assets that are
// definitely in the cache are reported as missing and the app fails to start offline.
const MATCH_OPTIONS = { ignoreSearch: true, ignoreVary: true };

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);

      // The page, asked for fresh and answered from the cache only when there is no
      // answer from the network. Every other file here is named after its contents,
      // so the cache can never hold a wrong one; the page is named `/` no matter what
      // it says, and serving that from the cache first is how a deploy stays invisible
      // to somebody who already has the app.
      //
      // The network copy is deliberately not written into the cache. What the cache
      // holds is one deploy's page and that same deploy's assets, put there together
      // by an install; storing a newer page beside older assets would make an app that
      // works until the connection goes and then does not start at all.
      if (request.mode === 'navigate') {
        try {
          const fresh = await fetch(new Request('/', { cache: 'reload' }));
          if (fresh.ok) return fresh;
        } catch {
          // No network. The cached page below is the whole point of having one.
        }

        const shell = await cache.match('/', MATCH_OPTIONS);
        if (shell) return shell;
      }

      const hit = await cache.match(request, MATCH_OPTIONS);
      if (hit) return hit;

      try {
        return await fetch(request);
      } catch {
        return new Response('Offline and not in cache.', {
          status: 504,
          headers: { 'Content-Type': 'text/plain' },
        });
      }
    })(),
  );
});
