/* Generated by serviceWorkerPlugin. Do not edit by hand. */
const CACHE = 'tarsia-593e38ae35845f3e';
const PRECACHE = [
  "/",
  "/assets/index-D9soiRO_.css",
  "/assets/index-rXZzk6Gx.js",
  "/fonts/instrument-sans.woff2",
  "/fonts/instrument-serif-italic.woff2",
  "/fonts/instrument-serif.woff2",
  "/fonts/jetbrains-mono.woff2",
  "/icons/favicon.svg",
  "/icons/icon-180.png",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-512.png",
  "/manifest.webmanifest"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // addAll rejects the whole install if any single asset fails, which is what we
      // want: a half-populated cache would produce a broken app that appears to work.
      await cache.addAll(PRECACHE);
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name)));
      await self.clients.claim();
    })(),
  );
});

// Cached responses are looked up ignoring both the query string and the Vary header.
// Vary matters: many static hosts send `Vary: Origin` or `Vary: Accept-Encoding`, and
// with the default rules a stored response is only returned when the new request's
// headers match those of the request that stored it. Without this, assets that are
// definitely in the cache are reported as missing and the app fails to start offline.
const MATCH_OPTIONS = { ignoreSearch: true, ignoreVary: true };

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);

      // Navigations always resolve to the app shell so deep links work offline.
      if (request.mode === 'navigate') {
        const shell = await cache.match('/', MATCH_OPTIONS);
        if (shell) return shell;
      }

      const hit = await cache.match(request, MATCH_OPTIONS);
      if (hit) return hit;

      try {
        return await fetch(request);
      } catch {
        return new Response('Offline and not in cache.', {
          status: 504,
          headers: { 'Content-Type': 'text/plain' },
        });
      }
    })(),
  );
});
